version: '3'
services:
  app:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - .env
    networks:
      - mynetwork

  db:
    image: postgres:13.3
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynetwork

networks:
  mynetwork: